# Generated by Django 4.1.3 on 2022-11-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='reason',
        ),
        migrations.AddField(
            model_name='taskassighn',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
