# Generated by Django 4.1.3 on 2022-11-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_taskstatus_reason_taskassighn_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
