# Generated by Django 4.1.3 on 2022-11-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskstatus_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassighn',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
