# Generated by Django 4.1.3 on 2022-12-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskassighn_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskassighn'),
        ),
    ]
