# Generated by Django 4.1.3 on 2022-12-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskstatus_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='state',
            field=models.CharField(blank=True, choices=[('منجزة', 'منجزة'), ('غير منجزة', 'غير منجزة'), ('تحت الإجراء', 'تحت الإجراء')], max_length=20, null=True),
        ),
    ]
