# Generated by Django 4.1.3 on 2022-12-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_taskassighn_reason_remove_taskassighn_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='state',
            field=models.CharField(choices=[('منجزة', 'منجزة'), ('غير منجزة', 'غير منجزة'), ('تحت الإجراء', 'تحت الإجراء')], max_length=20, null=True),
        ),
    ]
