# Generated by Django 4.1.3 on 2022-12-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_taskstatus_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='reason',
        ),
        migrations.AddField(
            model_name='taskassighn',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taskassighn',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.taskstatus'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='state',
            field=models.CharField(blank=True, choices=[('منجزة', 'منجزة'), ('غير منجزة', 'غير منجزة'), ('تحت الإجراء', 'تحت الإجراء')], max_length=20, null=True),
        ),
    ]
