# Generated by Django 4.1.3 on 2022-12-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_taskassighn_reason_taskstatus_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassighn',
            name='author',
        ),
        migrations.RemoveField(
            model_name='taskassighn',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='taskassighn',
            name='time_start',
        ),
        migrations.AddField(
            model_name='taskassighn',
            name='task_number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='state',
            field=models.CharField(blank=True, choices=[('تحت الإجراء', 'تحت الإجراء'), ('منجزة', 'منجزة'), ('غير منجزة', 'غير منجزة')], default='تحت الإجراء', max_length=20, null=True),
        ),
    ]
