# Generated by Django 4.1.3 on 2022-12-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_taskassighn_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='task',
        ),
        migrations.AddField(
            model_name='taskassighn',
            name='reason',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
