# Generated by Django 4.1.3 on 2022-12-07 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_employeeadd_taskassighn_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassighn',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.employeeadd'),
        ),
        migrations.AlterField(
            model_name='taskassighn',
            name='task_number',
            field=models.PositiveIntegerField(auto_created=True, null=True, unique=True),
        ),
    ]
