# Generated by Django 4.1.3 on 2022-12-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_taskassighn_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassighn',
            name='url',
        ),
        migrations.AlterField(
            model_name='taskassighn',
            name='task_number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
